"""
Chat API endpoints.

Phase 1: Direct provider chat with streaming support.
Phase 3: This will be replaced by the Agent workflow endpoint.
"""

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from backend.schemas.chat import ChatRequest, ChatResponse
from backend.services.provider_registry import ProviderRegistry

router = APIRouter(prefix="/chat", tags=["chat"])


@router.post("/stream")
async def chat_stream(request: ChatRequest):
    """
    Streaming chat endpoint using Server-Sent Events (SSE).

    Returns tokens as they're generated by the LLM.
    Frontend can consume this with EventSource or fetch + ReadableStream.
    """
    try:
        provider = ProviderRegistry.get_provider(request.provider)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    async def event_generator():
        async for token in provider.stream_chat(request.messages, request.temperature):
            # SSE format: data: <json>\n\n
            yield f"data: {token}\n\n"
        yield "data: [DONE]\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.post("/completions", response_model=ChatResponse)
async def chat_completions(request: ChatRequest):
    """
    Non-streaming chat endpoint.
    Returns the complete response after the LLM finishes generating.
    """
    try:
        provider = ProviderRegistry.get_provider(request.provider)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    content = await provider.chat(request.messages, request.temperature)
    return ChatResponse(content=content, provider=provider.name, model=provider.model)


@router.get("/providers")
async def list_providers():
    """List all available LLM providers."""
    return {
        "providers": ProviderRegistry.list_providers(),
        "default": ProviderRegistry.get_provider().name,
    }
